### ISSUE TITLE
BO - New Strapi Structure and Collections

### ISSUE THREAD

**Issue by Seblecaribou** [WildCodeSchool/lyon-p3-sens-interdit#109]
Since the project is more oriented towards a CMS than a "static" website, a lot of pages need to be administrable. In that regard, we need a structure that is more easy to use for the client than what we had previously thought of.

This task consist of creating the new collections needed:
- [x] **Spectacle** : for this one, add "place" (text), "country" (text), "new" (boolean set to true by default, that will help determine weither or not the spectacle was from the old website or created now)  and a component "price" as new fields. 
Also for the "infos pratiques", we need a field "logos partners" (component made of media and text to add a logo and url) and "logos sensi" (media/image). We also need a "infos" repeatable text that can be added.
- [ ] **News** (collection)
- [x] **Partners** (component): "name" and "logos" 
- [x] **Accessibility**(component): "name" and "logos" (component)
- [ ] **Global settings** : this one contains the logos and content of the header and footer, in case they need to change it
- [ ] **Association** (single type): tab_element (repeatable), "content/description" (text), "header image" (media/image)
- [ ] **Hors Scène** (single type):  "content/description" (text), tab_element (with Spectacle foreign_key)
- [ ] **Partners** (single type): "content/description" (text), "partner" (component made of "title" and "logos component")
- [ ] **Press** (single type): tab_element, "content/description" (txt)
